#!/usr/bin/env bash
#script that generates a MySQL dump and creates a compressed archive out of it

d=`date +%d-%m-%y`
sudo mysqldump -u root --password "$1" --all-databases > backup.sql
sudo gzip -c backup.sql > "$d".tar.gz
