#!/usr/bin/env bash
#displa 2 things when reciving 2 different signals
touch /var/run/myscript.pid
bash -c 'echo $$ > /var/run/myscript.pid'
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/myscript.pd; exit' SIGQUIT
    trap 'sudo rm /var/run/myscript.pd; exit' SIGTERM
done
