#!/usr/bin/env bash
#this script display 10 strings

I=1
while [ $I -lt 11 ]
do
 if [ $I == 4 ]
 then
 echo "bad luck"
 elif [ $I == 8 ]
 then
 echo "good luck"
 else
 echo "Best School"
 fi
 I=$(( I+1 ))
done
